/tmp/moidir

diff --git a/.github/workflows/random.yml b/.github/workflows/random.yml
--- a/.github/workflows/random.yml
+++ b/.github/workflows/random.yml
@@ -57,7 +57,8 @@ jobs:
       - name: check PATH
         run: |
           echo "Checking PATH..."
-          which new.sh || echo "new.sh not found"
           echo $PATH
+          which new.sh || echo "new.sh not found"
+          ls -lrt /tmp/moidir
       - name: last step
         run: echo "Ending..."
